//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqAdoNetDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Large_table_3
    {
        public int id { get; set; }
        public string color { get; set; }
        public string size { get; set; }
    }
}
