//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqAdoNetDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalStat
    {
        public int id { get; set; }
        public Nullable<double> dead_percent { get; set; }
        public Nullable<double> recovered_percent { get; set; }
    }
}
